services:
    _defaults:
        autowire: true
        autoconfigure: true

    InspiredMinds\ContaoAuthorNews\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection,ContaoAuthorNewsBundle.php}
